const special = {
    EMPTY: '',
    APOSTROPHE: '\'',
    SINGLE_QUOTE: '\'',
    DOUBLE_QUOTE: '\"',
    BACK_QUOTE: '\`',
    SLASH: '/',
    FORWARD_SLASH: '/',
    BACKSLASH: '\\',
    DOT: '.',
    COMMA: ',',
    QUESTION: '?',
    COLON: ':',
    SEMICOLON: ';',
    PIPE: '|',
    TILDE: '~',
    EXCLAMATION: '!',
    AT: '@',
    HASH: '#',
    DOLLAR: '$',
    PERCENT: '%',
    CARET: '^',
    AMPERSAND: '&',
    ASTERISK: '*',
    OPEN_PARENTHESIS: '(',
    CLOSE_PARENTHESIS: ')',
    MINUS: '-',
    HYPHEN: '-',
    DASH: '-',
    UNDERSCORE: '_',
    PLUS: '+',
    EQUAL: '=',
    ASSIGNMENT: '=',
    AND: '&&',
    OR: '||',
    OPEN_BRACE: '{',
    CLOSE_BRACE: '}',
    OPEN_CURLY_BRACKET: '{',
    CLOSE_CURLY_BRACKET: '}',
    OPEN_BRACKET: '[',
    CLOSE_BRACKET: ']',
    OPEN_ANGLE_BRACKET: '<',
    CLOSE_ANGLE_BRACKET: '>',
    LESS_THAN: '<',
    GREATER_THAN: '>'
};

module.exports = special;